alias c := clean

clean name:
    git push -d origin $(git branch  |  cat  -s | grep '{{ name }}' | sed -e 's/\*//g' -e 's/ *//g') || git branch -D  $( git branch  |  cat  -s | grep '{{ name }}' | sed -e 's/\*//g' -e 's/ *//g' )
